language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
sudo: required
addons:
  chrome: stable
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release